import { readFileSync } from "node:fs";
import path from "node:path";
import { build } from "esbuild";
import { expect, test } from "@playwright/test";

test("model switching changes real generator inputs, quality and duration controls", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  const fixture = (await build({ entryPoints: ["tests/browser/fixtures/kie-model-controls.tsx"], absWorkingDir: process.cwd(), tsconfig: path.resolve("tsconfig.json"), bundle: true, write: false, platform: "browser", jsx: "automatic", define: { "process.env.NODE_ENV": '"production"' } })).outputFiles[0].text;
  await page.setContent(`<style>${readFileSync("node_modules/@xyflow/react/dist/style.css", "utf8")}${readFileSync("src/app/globals.css", "utf8")}${readFileSync("src/app/theme.css", "utf8")}</style><div id="root"></div>`);
  await page.addScriptTag({ content: fixture });
  const card = page.locator(".frame-node--generator");
  await card.hover();
  await expect(card.getByRole("button", { name: "IMAGE MODELS", exact: true })).toBeVisible();
  await card.getByRole("button", { name: "QUALITY", exact: true }).click();
  await page.getByRole("button", { name: "4K", exact: true }).click();
  await card.getByRole("button", { name: "RATIO", exact: true }).click();
  await expect(page.getByRole("button", { name: "27:16", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "1:1", exact: true }).click();
  await page.getByRole("button", { name: "PixVerse", exact: true }).click();
  await card.hover();
  await expect(card.getByRole("button", { name: "DURATION", exact: true })).toBeVisible();
  await card.getByRole("button", { name: "QUALITY", exact: true }).click();
  await expect(page.getByRole("button", { name: "540P", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "540P", exact: true }).click();
  await card.getByRole("button", { name: "VIDEO MODELS", exact: true }).click();
  await page.getByRole("button", { name: /PixVerse V6 · Transition/ }).click();
  await expect(card.getByRole("button", { name: "RATIO", exact: true })).toHaveCount(0);
  await expect(card.locator(".generator-run")).toBeDisabled();
  await expect(card.getByText("Start frame", { exact: true }).first()).toBeVisible();
  await expect(card.getByText("End frame", { exact: true }).first()).toBeVisible();
  await page.getByRole("button", { name: "Omni", exact: true }).click();
  await card.hover();
  await expect(card.getByRole("button", { name: "DURATION", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Toggle video reference", exact: true }).click();
  await card.hover();
  await expect(card.getByRole("button", { name: "DURATION", exact: true })).toHaveCount(0);
  await expect(card.getByText("Auto duration", { exact: true })).toBeVisible();
  await expect(card.locator(".generator-sound-control")).toHaveCount(0);
  await expect(card.locator(".generator-credit-tooltip")).toContainText("168");
  await page.getByRole("button", { name: "Toggle video reference", exact: true }).click();
  await card.hover();
  await expect(card.getByRole("button", { name: "DURATION", exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
