import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import {
  generationPromptSystemInstruction,
  imagePromptSystemInstruction,
  videoPromptSystemInstruction,
} from "../src/lib/generation-prompt-system";
import { promptComposeRequestSchema } from "../src/lib/prompt-compose-request";

const projectId = "project-system-prompt";

test("generation assistant keeps the live default when no node override is saved", () => {
  const defaultPrompt = imagePromptSystemInstruction({ modelId: "nano-banana-2" });
  assert.equal(generationPromptSystemInstruction({ mediaType: "image", modelId: "nano-banana-2", references: [], systemPrompt: "" }), defaultPrompt);
});

test("custom generation instructions extend rather than replace required contracts", () => {
  const instruction = generationPromptSystemInstruction({
    mediaType: "video",
    modelId: "kling-3-motion",
    modelLabel: "Kling Motion",
    generateAudio: false,
    references: [{ role: "start-frame" }, { role: "reference-video" }],
    systemPrompt: "Use a quiet documentary tone and concise wording.",
  });
  assert.match(instruction, /reference video defines pose, body movement, timing and motion trajectory/i);
  assert.match(instruction, /CUSTOM SYSTEM INSTRUCTIONS/);
  assert.match(instruction, /quiet documentary tone/i);
  assert.match(instruction, /must not remove, contradict, or weaken the required reference/i);
});

test("the visible video default is generated by the same shared prompt builder", () => {
  const input = {
    modelId: "seedance-2-fast",
    modelLabel: "Seedance 2 Fast",
    duration: "8",
    generateAudio: true,
    references: [{ role: "start-frame" }, { role: "end-frame" }],
  };
  assert.equal(generationPromptSystemInstruction({ mediaType: "video", ...input }), videoPromptSystemInstruction(input));
});

test("prompt compose requests accept bounded per-node custom instructions", () => {
  const parsed = promptComposeRequestSchema.parse({ projectId, brief: "Create a quiet portrait", systemPrompt: "Prefer natural window light." });
  assert.equal(parsed.systemPrompt, "Prefer natural window light.");
  assert.equal(promptComposeRequestSchema.safeParse({ projectId, brief: "Create a quiet portrait", systemPrompt: "x".repeat(10_001) }).success, false);
});

test("generation-node settings expose default, custom, save, and one-click reset controls", () => {
  const frameNode = readFileSync(new URL("../src/components/FrameNode.tsx", import.meta.url), "utf8");
  const canvasApp = readFileSync(new URL("../src/components/CanvasApp.tsx", import.meta.url), "utf8");
  assert.match(frameNode, /System prompt settings/);
  assert.match(frameNode, /Scenelith default/);
  assert.match(frameNode, /Save custom/);
  assert.match(frameNode, /Reset to default/);
  assert.match(canvasApp, /systemPrompt: String\(generatorNode\?\.data\.systemPrompt \|\| ""\)/);
  assert.match(canvasApp, /systemPrompt: String\(master\.data\.systemPrompt \|\| ""\)/);
});
